### ISSUE TITLE
Normal Login still not working

### ISSUE THREAD

**Issue by DuckyQuack** [frozenpandaman/splatnet2statink#73] opened 2019-02-06 16:30 UTC

**Comment by frozenpandaman** [comment] 2019-02-06 18:18
More information would be helpful. What error are you getting? etc.

**Comment by frozenpandaman** [comment] 2019-02-07 02:07
I can't reproduce this:
```
eli:splatnet2statink eli$ ./splatnet2statink.py 
splatnet2statink v1.4.0
Pulling data from online...
The stored cookie has expired.
Attempting to generate new cookie...
Wrote iksm_session cookie for eli to config.txt.
Pulling data from online...
Number of recent battles to upload (0-50)? 
```

**Comment by frozenpandaman** [comment] 2019-02-08 23:34
Closing due to lack of information.

**Closed by frozenpandaman** 2019-02-08 23:34 UTC
