### ISSUE TITLE
mitmproxy still not working

### ISSUE THREAD

**Issue by Terax235** [frozenpandaman/splatnet2statink#68] opened 2018-11-01 18:21 UTC
Hello. I've tried to get the iksm_token using mitmproxy but it's not working.
I've set the proxy and everything, then I've opened http://mitm.it/ but it didn't show a certificate to install.

**Comment by frozenpandaman** [comment] 2018-11-01 18:59
Duplicate of #64, which you also created. Please keep conversation there.

While we'd like to help, and have tried to do so on that issue, this technically isn't splatnet2statink-related.

**Closed by frozenpandaman** 2018-11-01 18:59 UTC
